### ISSUE TITLE
[FeatureRequest]: extend the docs

### ISSUE THREAD

**Issue by racinmat** [avast/wanna-ml#111]
### Is your feature request related to a problem? Please describe

it's non-trivial to figure out the correct version and os for the vm_image
add more examples
e.g.
```yaml
    environment:
     vm_image:
       framework: common
       version: cpu
       os: v20240306-debian-11-py310
```
leads to 
`google.api_core.exceptions.NotFound: 404 The resource 'projects/deeplearning-platform-release/global/images/family/common-cpu-notebooks-v20240306-debian-11-py310' was not found`
and I don't know why it's wrong, if I should use the first or third column from the list

### Describe the solution you'd like

more examples like
```
    environment:
     vm_image:
       framework: pytorch
       version: 1-9-xla
       os: debian-10
```
and explaining how this maps to list of images listed by `gcloud compute images list --project deeplearning-platform-release | grep notebooks`, e.g.
```
common-cpu-notebooks-20200229                                  deeplearning-platform-release  common-cpu-notebooks-scheduler                                  READY
common-cpu-notebooks-v20201230-debian-9                        deeplearning-platform-release  common-cpu-notebooks-debian-9                                   READY
common-cpu-notebooks-v20211105-ubuntu-1804                     deeplearning-platform-release  common-cpu-notebooks-ubuntu-1804                                READY
common-cpu-notebooks-v20240306                                 deeplearning-platform-release  common-cpu-notebooks                                            READY
common-cpu-notebooks-v20240306-debian-11                       deeplearning-platform-release  common-cpu-notebooks-debian-11                                  READY
common-cpu-notebooks-v20240306-debian-11-py310                 deeplearning-platform-release  common-cpu-notebooks-debian-11-py310                            READY
common-cpu-notebooks-v20240306-py310                           deeplearning-platform-release  common-cpu-notebooks-py310                                      READY
common-cpu-notebooks-v20240306-ubuntu-2004                     deeplearning-platform-release  common-cpu-notebooks-ubuntu-2004                                READY
common-cpu-notebooks-v20240306-ubuntu-2004-py310               deeplearning-platform-release  common-cpu-notebooks-ubuntu-2004-py310                          READY
common-cu100-notebooks-20200302                                deeplearning-platform-release  common-cu100-notebooks-scheduler                                READY
common-cu100-notebooks-v20201231-debian-9                      deeplearning-platform-release  common-cu100-notebooks-debian-9                                 READY
```

### Describe alternatives you've considered

using 
```
    environment:
     vm_image:
       framework: common
       version: cpu
       os: debian-11-py310

```
worked for me, but it was trial and error and I don't know why this one works and the other one not
