### ISSUE TITLE
[Bug]: Inconsistent docs and error message for the removed `pipeline.pipeline_file` parameter

### ISSUE THREAD

**Issue by brozjakub** [avast/wanna-ml#132]
### Contact Details

jakub.broz@gendigital.com

### What happened?

`pipeline.pipeline_file` parameter (and corresponding branch) was apparently removed [here](https://github.com/avast/wanna-ml/pull/103/files#diff-099fed71bbbbfc1da47947dfeb4ff60a076d48a28df7f5dcce7c54e91101f8a2L286-L297) when migrating to Kubeflow pipelines 2.0.

When trying to use this parameter a confusing error message is shown: `ValueError: Can not compile kfp pipeline, pipeline_file or pipeline_function must be set.`

The [docs](https://avast.github.io/wanna-ml/tutorial/pipeline/#pipeline) also still inconsistently show that `pipeline_file` is a valid parameter.

I expected the docs to not include this parameter. I expected the error message to tell me that the parameter does not exist or that it is deprecated and that I should use `pipeline_function` parameter instead.

### wanna.yaml file

```yaml
...
pipelines:
  - name: wanna-dummy-project
    schedule:
      cron: 0 0 1 * *
    pipeline_file: pipeline/pipeline.py
    pipeline_params: pipeline/params.yaml
    docker_image_ref: [train]
...
```

### wanna-ml CLI command

```shell
wanna pipeline run --name wanna-dummy-project --profile test-profile --params pipeline/params.yaml --version test
```

### Relevant log output

```shell
ValueError: Can not compile kfp pipeline, pipeline_file or pipeline_function must be set.
```
